Repository kalviumcommunity/Container-Tracking-and-Port-Operations-Maersk-Hackathon, pull requests merged in 2025-09, with the labels that each got.

#3 [ DOCS ] Added ER-Diagram
  docs/ER-diagram.md
  docs/database-entity-relationships.md
Labels: Review effort 1/5

#5 [FEAT]: ORM Database Schema setup
  .gitignore
  Container-Tracking-and-Port-Operations-Maersk-Hackathon.sln
  backend/.env.example
  backend/Data/ApplicationDbContext.cs
  backend/Data/Seeding/DataSeeder.cs
  backend/Extensions/ServiceExtensions.cs
  backend/Migrations/20250929102229_InitialCreate.Designer.cs
  backend/Migrations/20250929102229_InitialCreate.cs
  backend/Migrations/20250929105905_UpdateSchemaToMatchDiagram.Designer.cs
  backend/Migrations/20250929105905_UpdateSchemaToMatchDiagram.cs
  backend/Migrations/ApplicationDbContextModelSnapshot.cs
  backend/Models/Berth.cs
  backend/Models/BerthAssignment.cs
  backend/Models/Container.cs
  backend/Models/Port.cs
  backend/Models/Ship.cs
  backend/Models/ShipContainer.cs
  backend/Program.cs
  backend/Properties/launchSettings.json
  backend/appsettings.Development.json
  backend/appsettings.Production.json
  backend/appsettings.json
  backend/backend.csproj
  backend/backend.http
  docs/database-entity-relationships.md
Labels: Review effort 4/5, Possible security concern

#6 [DOCS] Added logs and figma file.
  docs/logs/dhruvil-log.md
  docs/logs/snegan-log.md
  docs/ui-wireframes.md
Labels: Review effort 1/5

#7 [feat]: Initialized vue project & create home UI
  .gitignore
  Container-Tracking-and-Port-Operations-Maersk-Hackathon.sln
  backend/Data/Seeding/DataSeeder.cs
  backend/Program.cs
  backend/backend.csproj
  frontend/README.md
  frontend/index.html
  frontend/jsconfig.json
  frontend/package-lock.json
  frontend/package.json
  frontend/public/favicon.ico
  frontend/src/App.vue
  frontend/src/assets/main.css
  frontend/src/components/Dashboard.vue
  frontend/src/main.js
  frontend/src/router/index.ts
  frontend/vite.config.js
Labels: Possible security concern, Review effort 3/5
